import { aggregateCustomsDescriptions } from "@/lib/export-auditor/customs-description";
import {
  formatDeclarationDescriptionSource,
  normalizeDeclarationDescriptionSource,
  resolveLineDeclarationDescription,
} from "@/lib/export-auditor/declaration-description-display";
import { INVOICE_DATE_IN_FUTURE } from "@/lib/export-auditor/invoice-date-readiness";
import type {
  AuditIssue,
  DeclarationDescriptionSource,
  DeclarationLanguage,
  ExportAuditReport,
  HsAggregationReport,
  InvoiceSummary,
  MrnSummary,
  PositionTraceabilityLine,
  ShipmentSummary,
} from "@/lib/export-auditor/types";
import {
  formatSourcePositions,
  getTraceabilityLinesForHs,
  resolveAggregationUnit,
} from "@/lib/export-auditor/position-traceability";
import {
  formatHsSourceLabel,
  formatHsStatusLabel,
} from "@/lib/export-auditor/hs-classification-workflow";
import { formatHsVerificationStatusLabel } from "@/lib/export-auditor/hs-verification-engine";
import {
  formatDeclarationNumericValue,
  formatInvoiceValueDisplay,
} from "@/lib/export-auditor/parse-locale-number";
import { isPackagingLine, resolveInvoiceLineType } from "@/lib/export-auditor/service-line-detection";

function formatPackageFieldsForLine(line: PositionTraceabilityLine): {
  packageCount: string;
  packageType: string;
} {
  const description = line.description?.trim() ?? "";
  if (isPackagingLine(description)) {
    const countMatch = description.match(/\b(\d+)\s*(?:x\s*)?(?:pal|pallet|carton|ctn|box|crate)/i);
    const typeMatch = description.match(/\b(pallet|pal|carton|ctn|box|crate)s?\b/i);
    const typeRaw = typeMatch?.[1]?.toUpperCase() ?? "";
    const type =
      /PAL/.test(typeRaw) ? "PAL" : /CTN|CARTON/.test(typeRaw) ? "CTN" : /BOX/.test(typeRaw) ? "BOX" : /CRATE/.test(typeRaw) ? "CRT" : "";
    return {
      packageCount: countMatch?.[1] ?? "",
      packageType: type,
    };
  }
  const lineType = resolveInvoiceLineType(description);
  if (lineType === "SERVICE") {
    return { packageCount: "", packageType: "" };
  }
  return { packageCount: "", packageType: "" };
}

function formatAggregatedPackageFields(lines: PositionTraceabilityLine[]): {
  packageCount: string;
  packageType: string;
} {
  const parts: string[] = [];
  for (const line of lines) {
    const { packageCount, packageType } = formatPackageFieldsForLine(line);
    if (packageCount && packageType) {
      parts.push(`${packageCount} | ${packageType}`);
    }
  }
  if (parts.length === 0) return { packageCount: "", packageType: "" };
  const unique = [...new Set(parts)];
  if (unique.length === 1) {
    const [count, type] = unique[0]!.split(" | ");
    return { packageCount: count ?? "", packageType: type ?? "" };
  }
  return { packageCount: unique.map((p) => p.split(" | ")[0]).join(", "), packageType: unique.map((p) => p.split(" | ")[1]).join(", ") };
}

export const MRN_EXPORT_FOOTER = "Generated by ExportGateway Export Auditor";
export const DECLARATION_DESCRIPTION_DISCLAIMER =
  "Declaration descriptions are declarant assistance only. HS classification, origin, value, and weight govern customs liability.";
export const MRN_EXPORT_FOOTER_WITH_DISCLAIMER = `${MRN_EXPORT_FOOTER}\n${DECLARATION_DESCRIPTION_DISCLAIMER}`;
export const MRN_WORKSHEET_NAME = "DECLARATION PREPARATION";
export const TRACEABILITY_WORKSHEET_NAME = "TRACEABILITY";

/** @deprecated Use MRN_WORKSHEET_NAME — kept for backward-compatible tests during migration. */
export const LEGACY_MRN_WORKSHEET_NAME = "MRN Preparation";
/** @deprecated Use TRACEABILITY_WORKSHEET_NAME */
export const LEGACY_TRACEABILITY_WORKSHEET_NAME = "Line Traceability";

export const MRN_EXPORT_COLUMNS = [
  "HS Code",
  "Description",
  "Country Of Origin",
  "Preferential Origin",
  "Quantity",
  "Unit Of Measure",
  "Net Weight (KG)",
  "Value",
  "Currency",
  "Package Count",
  "Package Type",
  "Source Positions",
] as const;

/** @deprecated Verification columns — retained for legacy consumers only. */
export const MRN_EXPORT_VERIFICATION_COLUMNS = [
  "HS Status",
  "HS Source",
  "Invoice HS",
  "Wizard HS",
  "HS Verification Status",
  "Wizard Confidence",
  "Verification Reason",
] as const;

/** @deprecated Extended columns retained for legacy consumers — prefer MRN_EXPORT_COLUMNS. */
export const MRN_EXPORT_EXTENDED_COLUMNS = [
  "HS Code",
  "Original Description",
  "Declaration Description",
  "Quantity",
  "Net Weight",
  "Value EUR",
  "Country Of Origin",
  "Preferential Origin",
  "Source Positions",
  "Description Source",
  "Review Recommended",
] as const;

export const TRACEABILITY_EXPORT_COLUMNS = [
  "Position Number",
  "Original Description",
  "Declaration Description",
  "Invoice HS",
  "Final HS",
  "Wizard HS",
  "HS Source",
  "HS Verification Status",
  "Wizard Confidence",
  "Verification Reason",
  "Quantity",
  "Value",
  "Country Of Origin",
  "Preferential Origin",
  "Package Count",
  "Package Type",
  "Description Source",
  "Review Recommended",
] as const;

export interface MrnExportHeader {
  invoiceNumber: string;
  exporter: string;
  consignee: string;
  destinationCountry: string;
  incoterms: string;
  invoiceValue: string;
  grossWeight: string;
}

export interface MrnExportRow {
  hsCode: string;
  hsStatus: string;
  hsSource: string;
  invoiceHsCode: string;
  wizardHsCode: string;
  verificationStatus: string;
  wizardConfidence: string;
  verificationReason: string;
  originalDescription: string;
  declarationDescription: string;
  quantity: number;
  unitOfMeasure: string;
  netWeight: number | null;
  netWeightFormatted: string;
  valueEur: number;
  valueFormatted: string;
  countryOfOrigin: string;
  preferentialOrigin: string;
  currency: string;
  sourcePositions: string;
  packageCount: string;
  packageType: string;
  descriptionSource: string;
  reviewRecommended: string;
  /** @deprecated Legacy field — use originalDescription */
  aggregatedDescription?: string;
  /** @deprecated Legacy field — use originalDescription */
  productDescriptions?: string;
  /** @deprecated Legacy field — use declarationDescription */
  customsDescription?: string;
  /** @deprecated Legacy field */
  countriesOfOrigin?: string;
  /** @deprecated Legacy field */
  preferentialOriginStatus?: string;
  /** @deprecated Legacy field */
  totalQuantity?: number;
  /** @deprecated Legacy field */
  totalNetWeight?: number | null;
  /** @deprecated Legacy field */
  totalValue?: number;
}

export interface TraceabilityExportRow {
  positionNumber: number;
  originalDescription: string;
  declarationDescription: string;
  invoiceHsCode: string;
  finalHsCode: string;
  wizardHsCode: string;
  hsSource: string;
  verificationStatus: string;
  wizardConfidence: string;
  verificationReason: string;
  hsCode: string;
  quantity: number;
  value: number;
  countryOfOrigin: string;
  preferentialOrigin: string;
  packageCount: string;
  packageType: string;
  descriptionSource: string;
  reviewRecommended: string;
  /** @deprecated Legacy field */
  invoiceDescription?: string;
  /** @deprecated Legacy field */
  customsDescription?: string;
  /** @deprecated Legacy field */
  unit?: string;
  /** @deprecated Legacy field */
  origin?: string;
}

export interface MrnExportDataset {
  header: MrnExportHeader;
  rows: MrnExportRow[];
  traceabilityRows: TraceabilityExportRow[];
  exportLanguage: DeclarationLanguage;
}

export interface MrnExportOptions {
  language?: DeclarationLanguage;
}

function formatDecimal(value: number | null | undefined, decimals = 3): string {
  if (value == null) return "";
  return value.toFixed(decimals).replace(".", ",");
}

function formatNetWeightExport(value: number | null | undefined): string {
  if (value == null || value <= 0) return "";
  return value.toLocaleString("de-DE", {
    minimumFractionDigits: 3,
    maximumFractionDigits: 3,
  });
}

function formatMoney(value: number): string {
  return formatDeclarationNumericValue(value);
}

function formatPreferentialOriginExport(status: string): string {
  if (status === "YES" || status === "NO") return status;
  return "UNKNOWN";
}

function formatCountryOfOriginDisplay(
  row: Pick<HsAggregationReport["hsAggregation"][number], "countryOfOrigin" | "countriesOfOrigin">
): string {
  const fromList = [...new Set((row.countriesOfOrigin ?? []).filter(Boolean))].sort();
  if (fromList.length > 0) return fromList.join(", ");
  return row.countryOfOrigin?.trim() ?? "";
}

function formatQuantity(value: number): string {
  return Number.isInteger(value) ? String(value) : value.toFixed(2).replace(".", ",");
}

function deriveAggregateDescriptionSource(
  sources: (DeclarationDescriptionSource | string)[]
): DeclarationDescriptionSource {
  if (sources.length === 0) return "rule_based";
  const normalized = sources.map((source) => normalizeDeclarationDescriptionSource(source));
  const unique = new Set(normalized);
  if (unique.size === 1) return normalized[0];
  if (normalized.includes("user_edited")) return "user_edited";
  if (normalized.includes("hs_library")) return "hs_library";
  if (normalized.includes("ai_generated")) return "ai_generated";
  return "rule_based";
}

export function buildMrnExportHeader(
  invoiceSummary: InvoiceSummary,
  shipmentSummary: ShipmentSummary,
  currency: string
): MrnExportHeader {
  return {
    invoiceNumber: invoiceSummary.invoiceNumber,
    exporter: invoiceSummary.exporter,
    consignee: invoiceSummary.consignee,
    destinationCountry: invoiceSummary.destinationCountry,
    incoterms: invoiceSummary.incoterms,
    invoiceValue: formatInvoiceValueDisplay(invoiceSummary.invoiceValue, currency),
    grossWeight:
      shipmentSummary.grossWeightTotal != null
        ? `${formatDecimal(shipmentSummary.grossWeightTotal, 3)} ${shipmentSummary.grossWeightUnit || "kg"}`
        : "",
  };
}

function formatConfidence(value: number | null | undefined): string {
  if (value == null) return "";
  return `${value}%`;
}

function buildTraceabilityExportRows(
  traceabilityLines: PositionTraceabilityLine[],
  language: DeclarationLanguage
): TraceabilityExportRow[] {
  return [...traceabilityLines]
    .sort((a, b) => a.positionNumber - b.positionNumber)
    .map((line) => {
      const resolved = resolveLineDeclarationDescription(line, language);
      const packages = formatPackageFieldsForLine(line);
      return {
        positionNumber: line.positionNumber,
        originalDescription: line.description,
        declarationDescription: resolved.description,
        invoiceHsCode: line.invoiceHsCode ?? "",
        finalHsCode: line.finalHsCode ?? line.hsCode ?? "",
        wizardHsCode: line.wizardHsCode ?? "",
        hsSource: formatHsSourceLabel(line.hsSource),
        verificationStatus: formatHsVerificationStatusLabel(line.verificationStatus),
        wizardConfidence: formatConfidence(line.wizardConfidence),
        verificationReason: line.verificationReason ?? "",
        hsCode: line.finalHsCode ?? line.hsCode,
        quantity: line.quantity,
        value: line.value,
        countryOfOrigin: line.countryOfOrigin,
        preferentialOrigin: line.preferentialOrigin,
        packageCount: packages.packageCount,
        packageType: packages.packageType,
        descriptionSource: formatDeclarationDescriptionSource(resolved.source),
        reviewRecommended: line.descriptionReviewRecommended ? "Yes" : "",
        invoiceDescription: line.description,
        customsDescription: resolved.description,
        unit: line.unit ?? "",
        origin: line.countryOfOrigin,
      };
    });
}

/** Build declaration preparation export dataset — one row per HS aggregation entry. */
export function buildMrnExportDataset(
  report: ExportAuditReport,
  options: MrnExportOptions = {}
): MrnExportDataset | null {
  const { hsAggregationReport, invoiceSummary, shipmentSummary } = report;
  if (!hsAggregationReport?.hsAggregation?.length) return null;

  const exportLanguage = options.language ?? "en";
  const currency = invoiceSummary.currency || "EUR";
  const header = buildMrnExportHeader(
    invoiceSummary,
    shipmentSummary,
    currency
  );

  const rows: MrnExportRow[] = hsAggregationReport.hsAggregation.map((row) => {
    const sourceLines = getTraceabilityLinesForHs(
      row.hsCode,
      row,
      hsAggregationReport.traceabilityLines
    );
    const resolvedLines = sourceLines.map((line) =>
      resolveLineDeclarationDescription(line, exportLanguage)
    );
    const declarationDescriptions = resolvedLines.map((entry) => entry.description);
    const originalDescription = sourceLines.map((line) => line.description).join(" | ");
    const aggregatedDeclarationDescription = aggregateCustomsDescriptions(declarationDescriptions);
    const descriptionSource = deriveAggregateDescriptionSource(
      resolvedLines.map((entry) => entry.source)
    );
    const reviewRecommended = sourceLines.some((line) => line.descriptionReviewRecommended)
      ? "Yes"
      : "";
    const preferentialOrigin = formatPreferentialOriginExport(row.preferentialOrigin);
    const unitOfMeasure = resolveAggregationUnit(sourceLines);
    const countryDisplay = formatCountryOfOriginDisplay(row);
    const packages = formatAggregatedPackageFields(sourceLines);

    return {
      hsCode: row.hsCode,
      hsStatus: formatHsStatusLabel(row.hsStatus),
      hsSource: formatHsSourceLabel(row.hsSource),
      invoiceHsCode: row.invoiceHsCode ?? "",
      wizardHsCode: row.wizardHsCode ?? "",
      verificationStatus: formatHsVerificationStatusLabel(row.verificationStatus),
      wizardConfidence: formatConfidence(row.wizardConfidence),
      verificationReason: row.verificationReason ?? "",
      originalDescription,
      declarationDescription: aggregatedDeclarationDescription,
      quantity: row.totalQuantity,
      unitOfMeasure,
      netWeight: row.totalNetWeight,
      netWeightFormatted: formatNetWeightExport(row.totalNetWeight),
      valueEur: row.totalValue,
      valueFormatted: formatMoney(row.totalValue),
      countryOfOrigin: countryDisplay,
      preferentialOrigin,
      currency,
      sourcePositions: formatSourcePositions(row.sourcePositions),
      packageCount: packages.packageCount,
      packageType: packages.packageType,
      descriptionSource: formatDeclarationDescriptionSource(descriptionSource),
      reviewRecommended,
      aggregatedDescription: aggregatedDeclarationDescription,
      productDescriptions: originalDescription,
      customsDescription: aggregatedDeclarationDescription,
      countriesOfOrigin: row.countryOfOrigin || row.countriesOfOrigin.join(", "),
      preferentialOriginStatus: preferentialOrigin,
      totalQuantity: row.totalQuantity,
      totalNetWeight: row.totalNetWeight,
      totalValue: row.totalValue,
    };
  });

  return {
    header,
    rows,
    traceabilityRows: buildTraceabilityExportRows(
      hsAggregationReport.traceabilityLines,
      exportLanguage
    ),
    exportLanguage,
  };
}

export function isMrnExportReady(
  report: Pick<ExportAuditReport, "hsAggregationReport">,
  issues: AuditIssue[] = []
): boolean {
  if (issues.some((issue) => issue.field === INVOICE_DATE_IN_FUTURE)) {
    return false;
  }
  return (report.hsAggregationReport?.hsAggregation?.length ?? 0) > 0;
}

function escapeCsvCell(value: string): string {
  if (/[;"\n\r]/.test(value)) {
    return `"${value.replace(/"/g, '""')}"`;
  }
  return value;
}

function rowToCsvCells(row: MrnExportRow): string[] {
  return [
    row.hsCode,
    row.declarationDescription || row.originalDescription,
    row.countryOfOrigin,
    row.preferentialOrigin,
    formatQuantity(row.quantity),
    row.unitOfMeasure,
    row.netWeightFormatted,
    row.valueFormatted,
    row.currency,
    row.packageCount,
    row.packageType,
    row.sourcePositions,
  ];
}

function traceabilityRowToCsvCells(row: TraceabilityExportRow): string[] {
  return [
    String(row.positionNumber),
    row.originalDescription,
    row.declarationDescription,
    row.invoiceHsCode,
    row.finalHsCode,
    row.wizardHsCode,
    row.hsSource,
    row.verificationStatus,
    row.wizardConfidence,
    row.verificationReason,
    formatQuantity(row.quantity),
    formatMoney(row.value),
    row.countryOfOrigin,
    row.preferentialOrigin,
    row.packageCount,
    row.packageType,
    row.descriptionSource,
    row.reviewRecommended,
  ];
}

/** Generate declaration preparation CSV — UTF-8 with BOM, semicolon delimiter. */
export function generateMrnCsv(
  report: ExportAuditReport,
  options: MrnExportOptions = {}
): string {
  const dataset = buildMrnExportDataset(report, options);
  if (!dataset) {
    throw new Error("No HS aggregation data available for declaration export.");
  }

  const lines: string[] = [];
  const { header, rows, traceabilityRows } = dataset;

  lines.push(`Invoice Number;${escapeCsvCell(header.invoiceNumber)}`);
  lines.push(`Exporter;${escapeCsvCell(header.exporter)}`);
  lines.push(`Consignee;${escapeCsvCell(header.consignee)}`);
  lines.push(`Destination Country;${escapeCsvCell(header.destinationCountry)}`);
  lines.push(`Incoterms;${escapeCsvCell(header.incoterms)}`);
  lines.push(`Invoice Value;${escapeCsvCell(header.invoiceValue)}`);
  lines.push(`Gross Weight;${escapeCsvCell(header.grossWeight)}`);
  lines.push("");
  lines.push(MRN_EXPORT_COLUMNS.join(";"));
  for (const row of rows) {
    lines.push(rowToCsvCells(row).map(escapeCsvCell).join(";"));
  }
  lines.push("");
  lines.push(TRACEABILITY_EXPORT_COLUMNS.join(";"));
  for (const row of traceabilityRows) {
    lines.push(traceabilityRowToCsvCells(row).map(escapeCsvCell).join(";"));
  }
  lines.push("");
  lines.push(escapeCsvCell(MRN_EXPORT_FOOTER_WITH_DISCLAIMER));

  return `\uFEFF${lines.join("\r\n")}`;
}

function buildExcelAoA(dataset: MrnExportDataset): (string | number)[][] {
  const { header, rows } = dataset;
  const aoa: (string | number)[][] = [
    ["Invoice Number", header.invoiceNumber],
    ["Exporter", header.exporter],
    ["Consignee", header.consignee],
    ["Destination Country", header.destinationCountry],
    ["Incoterms", header.incoterms],
    ["Invoice Value", header.invoiceValue],
    ["Gross Weight", header.grossWeight],
    [],
    [...MRN_EXPORT_COLUMNS],
  ];

  for (const row of rows) {
    aoa.push([
      row.hsCode,
      row.declarationDescription || row.originalDescription,
      row.countryOfOrigin,
      row.preferentialOrigin,
      row.quantity,
      row.unitOfMeasure,
      row.netWeightFormatted,
      row.valueFormatted,
      row.currency,
      row.packageCount,
      row.packageType,
      row.sourcePositions,
    ]);
  }

  aoa.push([]);
  aoa.push([MRN_EXPORT_FOOTER]);
  aoa.push([DECLARATION_DESCRIPTION_DISCLAIMER]);
  return aoa;
}

function buildTraceabilityExcelAoA(traceabilityRows: TraceabilityExportRow[]): (string | number)[][] {
  const aoa: (string | number)[][] = [[...TRACEABILITY_EXPORT_COLUMNS]];
  for (const row of traceabilityRows) {
    aoa.push([
      row.positionNumber,
      row.originalDescription,
      row.declarationDescription,
      row.invoiceHsCode,
      row.finalHsCode,
      row.wizardHsCode,
      row.hsSource,
      row.verificationStatus,
      row.wizardConfidence,
      row.verificationReason,
      row.quantity,
      row.value,
      row.countryOfOrigin,
      row.preferentialOrigin,
      row.packageCount,
      row.packageType,
      row.descriptionSource,
      row.reviewRecommended,
    ]);
  }
  return aoa;
}

/** Generate declaration preparation Excel workbook buffer (.xlsx). */
export async function generateMrnExcelBuffer(
  report: ExportAuditReport,
  options: MrnExportOptions = {}
): Promise<ArrayBuffer> {
  const dataset = buildMrnExportDataset(report, options);
  if (!dataset) {
    throw new Error("No HS aggregation data available for declaration export.");
  }

  const XLSX = await import("xlsx");
  const mrnWorksheet = XLSX.utils.aoa_to_sheet(buildExcelAoA(dataset));
  const traceabilityWorksheet = XLSX.utils.aoa_to_sheet(
    buildTraceabilityExcelAoA(dataset.traceabilityRows)
  );
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, mrnWorksheet, MRN_WORKSHEET_NAME);
  XLSX.utils.book_append_sheet(workbook, traceabilityWorksheet, TRACEABILITY_WORKSHEET_NAME);
  return XLSX.write(workbook, { bookType: "xlsx", type: "array" }) as ArrayBuffer;
}

export function mrnExportFilename(report: ExportAuditReport, extension: "csv" | "xlsx"): string {
  const base = report.invoiceSummary.invoiceNumber.replace(/[^\w.-]+/g, "_") || "invoice";
  return `declaration-preparation-${base}.${extension}`;
}

export function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  anchor.click();
  URL.revokeObjectURL(url);
}

export async function downloadMrnCsv(
  report: ExportAuditReport,
  options: MrnExportOptions = {}
): Promise<void> {
  const csv = generateMrnCsv(report, options);
  const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
  downloadBlob(blob, mrnExportFilename(report, "csv"));
}

export async function downloadMrnExcel(
  report: ExportAuditReport,
  options: MrnExportOptions = {}
): Promise<void> {
  const buffer = await generateMrnExcelBuffer(report, options);
  const blob = new Blob([buffer], {
    type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  });
  downloadBlob(blob, mrnExportFilename(report, "xlsx"));
}

/** Summary helper for tests — validates aggregation rows have source positions. */
export function assertExportRowsHaveSourcePositions(dataset: MrnExportDataset): boolean {
  return dataset.rows.every((row) => row.sourcePositions.length > 0);
}

export function summarizeMrnExport(report: HsAggregationReport & { mrnSummary: MrnSummary }): {
  rowCount: number;
  allTraceable: boolean;
} {
  const allHaveSources = report.hsAggregation.every((row) => row.sourcePositions.length > 0);
  return {
    rowCount: report.hsAggregation.length,
    allTraceable: allHaveSources,
  };
}

export function summarizeDeclarationDescriptionSources(dataset: MrnExportDataset): Record<
  string,
  number
> {
  const counts: Record<string, number> = {};
  for (const row of dataset.rows) {
    counts[row.descriptionSource] = (counts[row.descriptionSource] ?? 0) + 1;
  }
  for (const row of dataset.traceabilityRows) {
    counts[row.descriptionSource] = (counts[row.descriptionSource] ?? 0) + 1;
  }
  return counts;
}
