import unicodedata


COUNTRY_ALIASES = {
    "slovenija": "slovenia",
    "slovenia": "slovenia",
    "slo": "slovenia",
    "nemcija": "germany",
    "germany": "germany",
    "deutschland": "germany",
    "hrvaska": "croatia",
    "croatia": "croatia",
    "srbija": "serbia",
    "serbia": "serbia",
    "avstrija": "austria",
    "austria": "austria",
    "osterreich": "austria",
    "italija": "italy",
    "italy": "italy",
    "madzarska": "hungary",
    "hungary": "hungary",
    "francija": "france",
    "france": "france",
    "spanija": "spain",
    "spain": "spain",
    "poljska": "poland",
    "poland": "poland",
    "ceska": "czechia",
    "czechia": "czechia",
    "czech republic": "czechia",
    "slovaska": "slovakia",
    "slovakia": "slovakia",
    "romunija": "romania",
    "romania": "romania",
    "nizozemska": "netherlands",
    "netherlands": "netherlands",
    "belgija": "belgium",
    "belgium": "belgium",
    "bolgarija": "bulgaria",
    "bulgaria": "bulgaria",
    "ciper": "cyprus",
    "cyprus": "cyprus",
    "danska": "denmark",
    "denmark": "denmark",
    "estonija": "estonia",
    "estonia": "estonia",
    "finska": "finland",
    "finland": "finland",
    "grcija": "greece",
    "greece": "greece",
    "irska": "ireland",
    "ireland": "ireland",
    "latvija": "latvia",
    "latvia": "latvia",
    "litva": "lithuania",
    "lithuania": "lithuania",
    "luksemburg": "luxembourg",
    "luxembourg": "luxembourg",
    "malta": "malta",
    "portugalska": "portugal",
    "portugal": "portugal",
    "svedska": "sweden",
    "sweden": "sweden",
}


def normalize_country(value: str) -> str:
    normalized = unicodedata.normalize("NFKD", value.strip().lower())
    ascii_value = "".join(char for char in normalized if not unicodedata.combining(char))
    ascii_value = " ".join(ascii_value.replace(",", " ").split())
    return COUNTRY_ALIASES.get(ascii_value, ascii_value)
